### ISSUE TITLE
How can I increase the height of the black lines in the 3d .obj file

### ISSUE THREAD

**Issue by KaeYan** [jonivesto/java-png-to-obj#1]
Hi 

I am able to convert my png file to obj file. However, when i view the obj file, its flat. 

How can I actually increase the height of the lines in the obj file when generating? Thanks

Desired Result:
![image](https://user-images.githubusercontent.com/26451899/82854860-3d171b00-9f3c-11ea-9091-c36c857f9f74.png)

Current Result: 
![image](https://user-images.githubusercontent.com/26451899/82854903-5ddf7080-9f3c-11ea-9fae-efe1d63fae62.png)

**Comment by jonivesto** [comment]
This is something that can be done with 2 clicks in most 3d modeling programs. Making it flat was my intention and I feel like upgrading to 3d would totally kill the performance as this code is pretty messy 😄
